name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Dependencies
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v3
      steps:
    - name: Checkout
        uses: actions/checkout@v4
    - name: Install Dependencies
       run: npm install